jobmanager:
  rpc:
    address: codedstream-jobmanager
    port: 6123
  bind-host: 0.0.0.0
  memory:
    process:
      size: 1600m
  execution:
    failover-strategy: region

taskmanager:
  bind-host: 0.0.0.0
  numberOfTaskSlots: 10
  memory:
    process:
      size: 1728m
    managed:
      fraction: 0.4

parallelism:
  default: 1

rest:
  port: 8081
  address: 0.0.0.0

state:
  backend: rocksdb
  checkpoints:
    dir: s3://flink-checkpoints/checkpoints
  savepoints:
    dir: s3://flink-checkpoints/savepoints

execution:
  checkpointing:
    interval: 10s
    mode: EXACTLY_ONCE
    timeout: 10min
    min-pause: 5s
    max-concurrent-checkpoints: 1
    tolerable-failed-checkpoints: 3

restart-strategy:
  type: fixed-delay
  fixed-delay:
    attempts: 3
    delay: 10s

s3:
  endpoint: http://minio:9000
  path-style-access: true
  access-key: minio
  secret-key: minio123

sql-gateway:
  endpoint:
    rest:
      address: 0.0.0.0
      port: 8083